services:
  ollama:
    # image: ollama/ollama:latest
    image: ollama/ollama:0.13.1
    container_name: ollama-chat
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3030:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open-webui-data:/app/backend/data
    depends_on:
      - ollama

  searxng:
    # image: searxng/searxng:latest
    image: searxng/searxng:2025.12.7-9d3ec9a2a
    container_name: searxng
    ports:
      - "8080:8080"
    volumes:
      - ./config/searxng:/etc/searxng:rw

volumes:
  ollama-data:
    name: shared-ollama-data
  open-webui-data:
